config/routes.rb
Rails.application.routes.draw do
  get 'messages/create'


  devise_for :users
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html




  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check
  get 'search', to: 'searches#search', as: :search
  get 'users/show'
  get 'meetings/index'
  # Defines the root path route ("/")
  # root "posts#index"
  # resources :searches, only: [:search]
  resources :users, only: [:show]
  resources :meetings, only: [:index]
  resources :relationships, only: [:create, :show] do
    resources :messages, only: [:create]
    resources :meetings, only: [:create]
    member do
      get :favorite
    end
  end

  get "dashboard", to: "pages#dashboard", as: "dashboard"
end

app/views/layouts/_filter_bar.html.erb
<div class="filter-bar">
  <div class="filter-button">
    <%= link_to dashboard_path(sort: 'city_asc'), class: 'sort-button' do %>
      <i class="fas fa-arrow-up arrow-icon"></i>
    <% end %>
    <span class="filter-text">City</span>
    <%= link_to dashboard_path(sort: 'city_desc'), class: 'sort-button' do %>
      <i class="fas fa-arrow-down arrow-icon"></i>
    <% end %>
  </div>
  <div class="filter-button">
    <%= link_to dashboard_path(sort: 'pace_asc'), class: 'sort-button' do %>
      <i class="fas fa-arrow-up arrow-icon"></i>
    <% end %>
    <span class="filter-text">Pace</span>
    <%= link_to dashboard_path(sort: 'pace_desc'), class: 'sort-button' do %>
      <i class="fas fa-arrow-down arrow-icon"></i>
    <% end %>
  </div>
</div>

app/views/layouts/_navbar.html.erb
<header class="header">
  <nav>
      <%= link_to dashboard_path do %>
        <%= image_tag 'logofinal.png', class: 'logo-img' %>
      <% end %>

    <div class="search-bar">
      <%= form_with url: search_path, method: :get, local: true, class: "search_loop" do |form| %>
        <%= form.text_field :query, placeholder: 'Search...', class: 'search-input' %>
        <span class="search-icon">
          <%= image_tag 'Search_lens_icon.png'%>
        </span>
        <% end %>
    </div>
    <div class="icons">
      <%#  <%= link_to notifications_path do  CREER LE PATH CORRESPONDANT !! %>
        <%= image_tag 'notification.png'%>
      <%#  <% end %>
      <%# <%= link_to profile_path(current_user) do  CREER LE PATH CORRESPONDANT !! %>
        <%= image_tag 'profil_icon.png'%>
      <%# <% end %>
    </div>
  </nav>
</header>

app/views/layouts/_sidebar.html.erb
<div class="sidebar">
  <div class="sidebar-header text-center">
    <% if @user.avatar.attached? %>
      <%= cl_image_tag @user.avatar.key, class: "avatar" %>
    <% else %>
      <%= image_tag "janesmith.jpg", class: "avatar" %>
    <% end %>
    <h3><%= "#{@user.first_name} #{@user.last_name}" %></h3>
  </div>
  <ul class="sidebar-details list-unstyled border-end">
    <div data-controller="dropdown">
      <li class="d-flex align-items-center justify-content-between mb-4 px-4 --cursor-pointer" data-dropdown-target="head" data-action="click->dropdown#toggleList">
        <i class="fa-solid fa-user-group fa-2x me-2" style="color: #7853DB;"></i>
        <%= @relationships.count %>
      </li>
      <div class="buddies-list d-none dropdown-content mb-3" data-dropdown-target="list">
        <% @relationships.each do |relationship| %>
        <div class="d-flex justify-content-center my-2 meeting-display">
          <% if relationship.asker == current_user %>
            <%= link_to "#{relationship.receiver.first_name} #{relationship.receiver.last_name}", user_path(relationship.receiver), class: 'text-decoration-none text-dark' %>
          <% else %>
            <%= link_to "#{relationship.asker.first_name} #{relationship.asker.last_name}", user_path(relationship.asker), class: 'text-decoration-none text-dark' %>
          <% end %>

        </div>
        <% end %>
      </div>
    </div>
    <div data-controller="dropdown">
      <li class="d-flex align-items-center justify-content-between mb-4 px-4 --cursor-pointer" data-dropdown-target="head" data-action="click->dropdown#toggleList">
        <i class="fa-regular fa-handshake fa-2x me-2" style="color: #7853DB;"></i>
        <%= @meetings.count %>
      </li>
      <div class="meetings-list d-none dropdown-content mb-3" data-dropdown-target="list">
        <% @meetings.each do |meeting| %>
        <div class="d-flex justify-content-center my-2 meeting-display">
          <%= meeting.date %>, <%= meeting.time.strftime("%H:%M") %>
          in <%= meeting.location %>
        </div>
        <% end %>
      </div>
    </div>
    <li class="d-flex align-items-center justify-content-between mb-4 px-4">
      <i class="fa-solid fa-person-running fa-2x me-2" style="color: #7853DB;"></i>
      <%= @user.running_pace_minute_and_second %> / km
    </li>
    <li class="d-flex align-items-center justify-content-between mb-4 px-4">
      <i class="fa-regular fa-calendar fa-2x me-2" style="color: #7853DB;"></i>
      <%= @user.preference_date %>
    </li>
    <li class="d-flex align-items-center justify-content-between mb-4 px-4">
      <i class="fa-regular fa-clock fa-2x me-2" style="color: #7853DB;"></i>
      <%= @user.preference_hour %> pm
    </li>
    <li class="d-flex align-items-center justify-content-between mb-4 px-4">
      <i class="fa-solid fa-bullseye fa-2x me-2" style="color: #7853DB;"></i>
      <%= @user.next_official_running_event %>
    </li>
  </ul>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RunningBuddy</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload", media: 'all' %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/sweetalert2@11.7.1/dist/sweetalert2.min.css">
    <%= javascript_importmap_tags %>
    <%= favicon_link_tag 'Runningbuddy_logo.png', rel:"icon", type:"image/png"%>
    <title><%= meta_title %></title>
    <meta name="description" content="<%= meta_description %>">

    <meta property="og:title" content="<%= meta_title %>"/>
    <meta property="og:type" content="website"/>
    <meta property="og:url" content="<%= request.original_url %>" />
    <meta property="og:image" content="<%= meta_image %>" />
    <meta property="og:description" content="<%= meta_description %>" />
    <meta property="og:site_name" content="<%= meta_title %>" />

    <meta name="twitter:card" content="summary_large_image">
    <meta name="twitter:site" content="<%= DEFAULT_META["twitter_account"] %>">
    <meta name="twitter:title" content="<%= meta_title %>">
    <meta name="twitter:description" content="<%= meta_description %>">
    <meta name="twitter:creator" content="<%= DEFAULT_META["twitter_account"] %>">
    <meta name="twitter:image:src" content="<%= meta_image %>">
  </head>

  <body>
    <%= render "shared/flashes" %>
    <% unless request.path == root_path %>
      <%= render "layouts/navbar" %>
    <% end %>

<div class= <%= "main-layout-container" if current_page?(dashboard_path) %>>
      <% if request.path == dashboard_path %>
        <%= render "layouts/sidebar" %>
      <% end %>

      <%= yield %>
    </div>
  </body>
  <the-script src="https://cdn.jsdelivr.net/npm/sweetalert2@11.7.1/dist/sweetalert2.all.min.js"></the-script>
</html>